# CC Studio local .package prototype. Independent exporter does not load the S4S addon.
# Example: .\ccstudio-package.ps1 -Input .\object.glb -Name "My CC Object" -Price 10

param(
    [string]$Input = "",
    [string]$Name = "",
    [string]$Description = "Generated by CC Studio",
    [int]$Price = 1300,
    [string]$Recipe = "",
    [ValidateSet("s4s_local", "independent_local")][string]$MeshExporter = "s4s_local",
    [ValidateSet("python", "node")][string]$TextureEncoder = "python",
    [string]$Blender = "",
    [string]$Node = "",
    [switch]$Check,
    [double]$RotateX = 0,
    [double]$RotateY = 0,
    [double]$RotateZ = 0,
    [string]$Output = ""
)

$ErrorActionPreference = "Stop"
$inputPath = $PSBoundParameters["Input"]
if (-not $Check -and ([string]::IsNullOrWhiteSpace($Input) -or [string]::IsNullOrWhiteSpace($Name))) {
    Write-Error "Input and Name are required unless -Check is used."
    exit 1
}
$builder = Join-Path $PSScriptRoot "experiments\v03_build_package.py"
if (-not (Test-Path -LiteralPath $builder)) {
    Write-Error "Package builder not found: $builder"
    exit 1
}
$python = Get-Command python -ErrorAction SilentlyContinue
if (-not $python) {
    Write-Error "Python was not found on PATH."
    exit 1
}
$invariant = [System.Globalization.CultureInfo]::InvariantCulture
$arguments = @($builder, "--mesh-exporter", $MeshExporter,
               "--texture-encoder", $TextureEncoder)
if ($Check) {
    $arguments += "--check"
} else {
    $arguments += @(
        "--input", $inputPath,
        "--name", $Name,
        "--description", $Description,
        "--price", "$Price",
        "--rotate-x", $RotateX.ToString($invariant),
        "--rotate-y", $RotateY.ToString($invariant),
        "--rotate-z", $RotateZ.ToString($invariant)
    )
}
if (-not [string]::IsNullOrWhiteSpace($Blender)) {
    $arguments += @("--blender", $Blender)
}
if (-not [string]::IsNullOrWhiteSpace($Node)) {
    $arguments += @("--node", $Node)
}
if (-not [string]::IsNullOrWhiteSpace($Output)) {
    $arguments += @("--output", $Output)
}
if (-not [string]::IsNullOrWhiteSpace($Recipe)) {
    $arguments += @("--recipe", $Recipe)
}
& $python.Source @arguments
exit $LASTEXITCODE
